### ISSUE TITLE
MessageCreateEvent does not trigger upon messages being sent in DMs

### ISSUE THREAD

**Issue by elainecao93** [Javacord/Javacord#732] opened 2021-04-04 22:08 UTC
Breaking bug in 3.2.0.

Using the example bot in the `readme.md`:

Expected behavior: When the bot is interacted with in DMs, the bot replies in DMs.

Actual behavior: The bot does not reply because the `MessageCreateEvent` does not trigger.

**Comment by Vampire** [comment] 2021-04-04 23:08
Duplicate of #707

**Closed by Vampire** 2021-04-04 23:08 UTC

**Comment by Bastian** [comment] 2021-04-06 20:14
I've just released version 3.3.0 that fixes this bug.
