### ISSUE TITLE
Packethandler can't handle CHANNEL_UPDATE and causes NullPointerException

### ISSUE THREAD

**Issue by HippoBaguette** [Javacord/Javacord#737] opened 2021-04-09 06:16 UTC
Version: 3.3.0
When I use a ServerChannelUpdater to remove the permissions of a user it causes a waring that says PacketHandler can't handle packet of type `CHANNEL_UPDATE` and a null pointer exception

Error message:
```
2021-04-09 05:52:23.364+0000 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"type":5,"topic":null,"position":3,"permission_overwrites":[{"type":0,"id":"825189682245664839","deny":"2048","allow":"0"}],"parent_id":"825191860858388520","nsfw":false,"name":"server-announcements","last_message_id":null,"id":"825191929452036100","guild_id":"825189682245664839","guild_hashes":{"version":1,"roles":{"hash":"Vf9DtZpVFSA"},"metadata":{"hash":"J1QHnGT6Emo"},"channels":{"hash":"HsG7ENau4FI"}}}) {shard=0} 
 java.lang.NullPointerException
    at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerTextChannel(ChannelUpdateHandler.java:326)
    at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:105)
    at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
    

```
Code:
```java
package commands;

import org.javacord.api.DiscordApi;
import org.javacord.api.entity.channel.*;
import org.javacord.api.entity.message.embed.EmbedBuilder;
import org.javacord.api.entity.permission.PermissionType;
import org.javacord.api.entity.user.User;

import java.awt.Color;
import java.util.Optional;

public class EndTicketCommand {
    public static DiscordApi api;

    public EndTicketCommand(DiscordApi discordapi) {
        api = discordapi;
        api.addMessageCreateListener(event-> {


            if (event.getMessageContent().startsWith("-archive")) {
                if(!event.getMessage().getMentionedUsers().isEmpty()) {


                    Optional<ServerTextChannel> channel = event.getServerTextChannel();
                    if (channel.isPresent()) {
                        api.getChannelCategoryById("825224792072126494").ifPresent(channelCategory -> {
                            channel.get().updateCategory(channelCategory);

                        });
                        ServerChannelUpdater updater = new ServerChannelUpdater(event.getServerTextChannel().flatMap(Channel::asServerChannel).get());
                        updater.removePermissionOverwrite(event.getMessage().getMentionedUsers().get(0));

                    }
                }
            }
        });
    }

}

```

**Comment by KILLEliteMaste** [comment] 2021-04-10 09:02
I can't see how this line could throw an error. I also tried to reproduce it and everything worked like it should.
Did this happen to you only once or multiple times?

**Comment by Joshix-1** [comment] 2021-04-10 09:07
Did you try it with a channel of type 5?

**Comment by KILLEliteMaste** [comment] 2021-04-10 09:37
> Did you try it with a channel of type 5?
Thanks for the hint, I did not! And the error will be thrown. The error is due to the ServerNewsChannel being handled the same as a ServerTextChannel. A ServerNewsChannel does not have a `rate_limit_per_user` field. To fix it either check if the field is present or better (also shown in the discord docs) handle the ServerNewsChannel separately.

**Comment by dylhack** [comment] 2021-05-22 18:36
I received the same exception
```java
2021-05-22 11:28:21.557-0700 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"type":5,"topic":"We announce Videos uploads from PewDiePie here. (Also the members only ones)","position":36,"permission_overwrites":[{"type":0,"id":"718433475828645928","deny":"6209","allow":"0"},{"type":0,"id":"718464650194452511","deny":"0","allow":"66624"},{"type":0,"id":"720601652549386277","deny":"2099264","allow":"0"},{"type":0,"id":"729761460644872334","deny":"0","allow":"68609"},{"type":0,"id":"787096008814493706","deny":"0","allow":"1024"},{"type":0,"id":"791055362232418304","deny":"0","allow":"1024"}],"parent_id":"718451089459904543","nsfw":false,"name":"📹┃uploads","last_message_id":"845592912112779294","id":"718450656368656424","guild_id":"718433475828645928","guild_hashes":{"version":1,"roles":{"hash":"jD9eYQcBuDk"},"metadata":{"hash":"hK8ztFFrUtY"},"channels":{"hash":"Ny55vto3pjg"}}}) {shard=0} 
 java.lang.NullPointerException
	at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerTextChannel(ChannelUpdateHandler.java:326)
	at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:105)
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
2021-05-22 11:28:21.577-0700 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"type":5,"topic":"We announce livestreams from PewDiePie here.","position":37,"permission_overwrites":[{"type":0,"id":"718433475828645928","deny":"6209","allow":"0"},{"type":0,"id":"718464650194452511","deny":"0","allow":"66624"},{"type":0,"id":"720601652549386277","deny":"2099264","allow":"0"},{"type":0,"id":"729761460644872334","deny":"0","allow":"68673"},{"type":0,"id":"787096008814493706","deny":"0","allow":"66560"},{"type":0,"id":"791055362232418304","deny":"0","allow":"1024"}],"parent_id":"718451089459904543","nsfw":false,"name":"🔴┃livestreams","last_message_id":"845593438791008266","id":"718450669127860236","guild_id":"718433475828645928","guild_hashes":{"version":1,"roles":{"hash":"jD9eYQcBuDk"},"metadata":{"hash":"hK8ztFFrUtY"},"channels":{"hash":"KeaJMsZTuYg"}}}) {shard=0} 
 java.lang.NullPointerException
	at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerTextChannel(ChannelUpdateHandler.java:326)
	at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:105)
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

Here's the packet
```json
{
  "type": 5,
  "topic": "We announce Videos uploads from PewDiePie here. (Also the members only ones)",
  "position": 36,
  "permission_overwrites": [
    {
      "type": 0,
      "id": "718433475828645928",
      "deny": "6209",
      "allow": "0"
    },
    {
      "type": 0,
      "id": "718464650194452511",
      "deny": "0",
      "allow": "66624"
    },
    {
      "type": 0,
      "id": "720601652549386277",
      "deny": "2099264",
      "allow": "0"
    },
    {
      "type": 0,
      "id": "729761460644872334",
      "deny": "0",
      "allow": "68609"
    },
    {
      "type": 0,
      "id": "787096008814493706",
      "deny": "0",
      "allow": "1024"
    },
    {
      "type": 0,
      "id": "791055362232418304",
      "deny": "0",
      "allow": "1024"
    }
  ],
  "parent_id": "718451089459904543",
  "nsfw": false,
  "name": "📹┃uploads",
  "last_message_id": "845592912112779294",
  "id": "718450656368656424",
  "guild_id": "718433475828645928",
  "guild_hashes": {
    "version": 1,
    "roles": {
      "hash": "jD9eYQcBuDk"
    },
    "metadata": {
      "hash": "hK8ztFFrUtY"
    },
    "channels": {
      "hash": "Ny55vto3pjg"
    }
  }
}
```

**Comment by dylhack** [comment] 2021-05-22 18:41
Hi I'm using Javacord [v3.3.0](https://github.com/Javacord/Javacord/releases/tag/v3.3.0) and I received this exception today

```java
2021-05-22 11:28:21.557-0700 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"type":5,"topic":"We announce Videos uploads from PewDiePie here. (Also the members only ones)","position":36,"permission_overwrites":[{"type":0,"id":"718433475828645928","deny":"6209","allow":"0"},{"type":0,"id":"718464650194452511","deny":"0","allow":"66624"},{"type":0,"id":"720601652549386277","deny":"2099264","allow":"0"},{"type":0,"id":"729761460644872334","deny":"0","allow":"68609"},{"type":0,"id":"787096008814493706","deny":"0","allow":"1024"},{"type":0,"id":"791055362232418304","deny":"0","allow":"1024"}],"parent_id":"718451089459904543","nsfw":false,"name":"📹┃uploads","last_message_id":"845592912112779294","id":"718450656368656424","guild_id":"718433475828645928","guild_hashes":{"version":1,"roles":{"hash":"jD9eYQcBuDk"},"metadata":{"hash":"hK8ztFFrUtY"},"channels":{"hash":"Ny55vto3pjg"}}}) {shard=0} 
 java.lang.NullPointerException
	at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerTextChannel(ChannelUpdateHandler.java:326)
	at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:105)
	at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

JSON body:
```json
{
  "type": 5,
  "topic": "We announce Videos uploads from PewDiePie here. (Also the members only ones)",
  "position": 36,
  "permission_overwrites": [
    {
      "type": 0,
      "id": "718433475828645928",
      "deny": "6209",
      "allow": "0"
    },
    {
      "type": 0,
      "id": "718464650194452511",
      "deny": "0",
      "allow": "66624"
    },
    {
      "type": 0,
      "id": "720601652549386277",
      "deny": "2099264",
      "allow": "0"
    },
    {
      "type": 0,
      "id": "729761460644872334",
      "deny": "0",
      "allow": "68609"
    },
    {
      "type": 0,
      "id": "787096008814493706",
      "deny": "0",
      "allow": "1024"
    },
    {
      "type": 0,
      "id": "791055362232418304",
      "deny": "0",
      "allow": "1024"
    }
  ],
  "parent_id": "718451089459904543",
  "nsfw": false,
  "name": "📹┃uploads",
  "last_message_id": "845592912112779294",
  "id": "718450656368656424",
  "guild_id": "718433475828645928",
  "guild_hashes": {
    "version": 1,
    "roles": {
      "hash": "jD9eYQcBuDk"
    },
    "metadata": {
      "hash": "hK8ztFFrUtY"
    },
    "channels": {
      "hash": "Ny55vto3pjg"
    }
  }
}
```

**Comment by Joshix-1** [comment] 2021-05-22 18:45
try using the development branch, as the pr fixing the issue is already merged.

**Comment by coaxial1** [comment] 2021-06-24 12:11
@KILLEliteMaste Can we close this issue since your merged the solution for it already?

**Closed** 2021-06-24 12:28 UTC
Labels: bug, medium priority
