### ISSUE TITLE
Thread support

### ISSUE THREAD

**Issue by taksan** [Javacord/Javacord#831] opened 2021-08-03 12:18 UTC
Does javacord has plan to add support to the new thread feature?

**Comment by ShindouMihou** [comment] 2021-08-03 12:21
Yes but when it will be implemented completely depends on who has time, who is able to implement it. I don't know who is working on the feature right now, but there could be one on it at this moment or none.

**Comment by coaxial1** [comment] 2021-08-03 14:52
Duplicate of #748

**Closed by coaxial1** 2021-08-03 14:52 UTC
