### ISSUE TITLE
While deleting roles: Couldn't handle packet of type CHANNEL_UPDATE.

### ISSUE THREAD

**Issue by KleinDevDE** [Javacord/Javacord#746] opened 2021-04-22 20:23 UTC
```
Javacord 3.3.0
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
```

```
2021-04-22 19:42:01.818+0000 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (pac
ket: {"type":5,"topic":"Wichtige Ankündigungen rund um das Hotel!","position":15,"permission_overwrites":[{"type":0,"id":"787468489484271640","deny":"805829713"
,"allow":"0"},{"type":0,"id":"787468994889121843","deny":"1","allow":"805829712"},{"type":0,"id":"787490839533322261","deny":"0","allow":"183376"},{"type":0,"id
":"787490916247273542","deny":"0","allow":"134144"},{"type":0,"id":"787490995892781088","deny":"4097","allow":"805825616"},{"type":0,"id":"787491451247394866","
deny":"805763089","allow":"66624"},{"type":0,"id":"788111233400176670","deny":"1","allow":"805829712"},{"type":0,"id":"791726167865688096","deny":"2112","allow"
:"0"}],"parent_id":"787473436221243452","nsfw":false,"name":"📌┇ankündigungen","last_pin_timestamp":"2021-03-08T20:30:22+00:00","last_message_id":"8331792530292
08064","id":"787477976627150858","guild_id":"787468489484271640","guild_hashes":{"version":1,"roles":{"hash":"bMgkJ1wD4k8"},"metadata":{"hash":"MQ60ajlAOoE"},"c
hannels":{"hash":"g1SzNhilKQo"}}})
 java.lang.NullPointerException
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerTextChannel(ChannelUpdateHandler.java:326)
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:105)
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

```
```
2021-04-22 19:42:13.977+0000 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"type":5,"topic":null,"position":17,"permission_overwrites":[{"type":0,"id":"787468489484271640","deny":"1115136","allow":"0"},{"type":0,"id":"787490839533322261","deny":"0","allow":"182272"},{"type":0,"id":"787490916247273542","deny":"0","allow":"182272"},{"type":0,"id":"787491451247394866","deny":"190464","allow":"328768"},{"type":0,"id":"788111233400176670","deny":"0","allow":"256000"},{"type":0,"id":"791726167865688096","deny":"3019307857","allow":"1024"},{"type":0,"id":"821186228027392000","deny":"0","allow":"519168"}],"parent_id":"787473436221243452","nsfw":false,"name":"🔊┇radio-news","last_message_id":"833416249148571689","id":"829318489042321408","guild_id":"787468489484271640","guild_hashes":{"version":1,"roles":{"hash":"bMgkJ1wD4k8"},"metadata":{"hash":"MQ60ajlAOoE"},"channels":{"hash":"izugIxcgakA"}}})
 java.lang.NullPointerException
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerTextChannel(ChannelUpdateHandler.java:326)
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:105)
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```
```2021-04-22 19:42:20.342+0000 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"type":5,"topic":"Wichtige Ankündigungen rund um das Hotel!","position":16,"permission_overwrites":[{"type":0,"id":"787468489484271640","deny":"805829713","allow":"0"},{"type":0,"id":"787468994889121843","deny":"1","allow":"805829712"},{"type":0,"id":"787490839533322261","deny":"0","allow":"183376"},{"type":0,"id":"787490916247273542","deny":"0","allow":"134144"},{"type":0,"id":"787490995892781088","deny":"4097","allow":"805825616"},{"type":0,"id":"787491451247394866","deny":"805763089","allow":"66624"},{"type":0,"id":"788111233400176670","deny":"1","allow":"805829712"},{"type":0,"id":"791726167865688096","deny":"2112","allow":"0"}],"parent_id":"787473436221243452","nsfw":false,"name":"📌┇ankündigungen","last_pin_timestamp":"2021-03-08T20:30:22+00:00","last_message_id":"833179253029208064","id":"787477976627150858","guild_id":"787468489484271640","guild_hashes":{"version":1,"roles":{"hash":"bMgkJ1wD4k8"},"metadata":{"hash":"MQ60ajlAOoE"},"channels":{"hash":"CshZk6sL4cI"}}})
 java.lang.NullPointerException
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerTextChannel(ChannelUpdateHandler.java:326)
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:105)
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```
```2021-04-22 19:42:23.857+0000 WARN org.javacord.core.util.gateway.PacketHandler Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"type":5,"topic":null,"position":18,"permission_overwrites":[{"type":0,"id":"787468489484271640","deny":"805829713","allow":"0"},{"type":0,"id":"787468994889121843","deny":"1","allow":"805829712"},{"type":0,"id":"787490839533322261","deny":"805572625","allow":"257088"},{"type":0,"id":"787490916247273542","deny":"805572625","allow":"257088"},{"type":0,"id":"787490995892781088","deny":"0","allow":"805829713"},{"type":0,"id":"787491451247394866","deny":"805763089","allow":"66624"},{"type":0,"id":"788111233400176670","deny":"1","allow":"805829712"},{"type":0,"id":"791726167865688096","deny":"2100288","allow":"0"}],"parent_id":"787473436221243452","nsfw":false,"name":"📨┇discord-news","last_message_id":"834872611375808563","id":"793978276577280030","guild_id":"787468489484271640","guild_hashes":{"version":1,"roles":{"hash":"bMgkJ1wD4k8"},"metadata":{"hash":"MQ60ajlAOoE"},"channels":{"hash":"YtZKdDtf/tY"}}})
 java.lang.NullPointerException
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handleServerTextChannel(ChannelUpdateHandler.java:326)
        at org.javacord.core.util.handler.channel.ChannelUpdateHandler.handle(ChannelUpdateHandler.java:105)
        at org.javacord.core.util.gateway.PacketHandler.lambda$handlePacket$0(PacketHandler.java:51)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Joshix-1** [comment] 2021-04-22 20:30
duplicate of #737, fixed with #743

**Closed** 2021-04-22 20:30 UTC
