### ISSUE TITLE
[Voicchannel] Move Bot -> Connection issues

### ISSUE THREAD

**Issue by MiggiV2** [Javacord/Javacord#706] opened 2021-02-03 09:58 UTC
When the bot is playing music in a vc and moved to another vc
-> cant reconnect to any vc -> "this.socket" is null
-> cant close audio connection -> "this.socket" is null

Just restart the bot, is helping.

audioConnection().close();
->
Exception in thread "Thread-3" java.lang.NullPointerException: Cannot invoke "org.javacord.core.util.gateway.AudioUdpSocket.stopSending()" because "this.socket" is null
	at org.javacord.core.util.gateway.AudioWebSocketAdapter.disconnect(AudioWebSocketAdapter.java:305)
	at org.javacord.core.audio.AudioConnectionImpl.close(AudioConnectionImpl.java:358)
	at de.mymiggi.discordbot.music.youtube.actions.util.helpers.SameChannelListener$1.lambda$0(SameChannelListener.java:59)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at de.mymiggi.discordbot.music.youtube.actions.util.helpers.SameChannelListener$1.run(SameChannelListener.java:48)

**Comment by Vampire** [comment] 2021-11-15 14:10
duplicate of #693

**Closed by Vampire** 2021-11-15 14:10 UTC
