### ISSUE TITLE
Removing embeds with images from a message by editing leaves the image as an attached file.

### ISSUE THREAD

**Issue by DAflamingFOX** [Javacord/Javacord#1037] opened 2022-06-25 21:47 UTC
When editing a message in such a way that it removes an embed, the embed is successfully removed, however any images attached are attached to the message still, no longer in the embed.

Images of it occurring: https://imgur.com/a/XVCCIrP

**Comment by Vampire** [comment] 2022-06-26 08:50
Duplicate of #933

**Closed** 2022-06-26 08:50 UTC
